### ISSUE TITLE
Falta do else{}

### ISSUE THREAD

**Issue by vitorsacramento** [acenelio/nivelamento-java#1]
Prezado professor Nélio, tudo bem?
Estava fazendo o exercício e verifiquei que falta o else{} para que a mensagem de "código inválido" possa ser impressa caso o range esteja fora do 1 ao 4. 

`import java.util.Locale;
import java.util.Scanner;

public class ExercicioEstruturaWhile2 {

	public static void main(String[] args) {
		Locale.setDefault(Locale.US);
		Scanner inputGas = new Scanner(System.in);

		System.out.println("---------------- POSTO DE GASOLINA -----------------");
		System.out.println("------------- COMBUSTÍVEIS DISPONÍVEIS -------------");
		System.out.println("----------------------------------------------------");
		System.out.println("1 - Álcool");
		System.out.println("2 - Gasolina");
		System.out.println("3 - Diesel");
		System.out.println("4 - SAIR");
		System.out.println("----------------------------------------------------");
		System.out.printf("Digite o código de seu combustível preferido: ");

		int code = inputGas.nextInt();
		int alcool = 0;
		int gasoline = 0;
		int diesel = 0;
		
		while(code != 4) {
			if(code == 1) {
				alcool = alcool + 1;
			}
			else if(code == 2) {
				gasoline = gasoline + 1;
			}
			else if(code == 3) {
				diesel = diesel + 1;
			}
			else {
				System.out.println("");
				System.out.println("----------------------------------------------------");	
				System.out.println("---------------- CÓDIGO INVÁLIDO! ------------------");
				System.out.println("----------------------------------------------------");
				System.out.println("");
			}
			
			
			System.out.printf("Digite o código de seu combustível preferido: ");
			code = inputGas.nextInt();	
		}
		System.out.println("");
		System.out.println("----------------------------------------------------");	
		System.out.println("------------- MUITO OBRIGADO! ----------------------");
		System.out.println("----------------------------------------------------");
		System.out.println("------------ TOTAL ABASTECIDO ----------------------");
		System.out.println("Álcool: " + alcool);
		System.out.println("Gasolina: " + gasoline);
		System.out.println("Diesel: " + diesel);
		System.out.println("----------------------------------------------------");
	}

}
`

**Comment by acenelio** [comment]
Caro Vitor, muito obrigado pela mensagem e parabéns pela dedicação aos estudos. 
Embora sua consideração seja muito pertinente e importante, na verdade este exercício não exige interação com o usuário nesse caso, conforme mostrado no exemplo do enunciado do exercício: observe no exemplo que, quando digitamos um número fora do intervalo 1-4, o programa simplesmente espera uma nova digitação, sem mostrar mensagem. Por este motivo que eu não coloquei um else a mais, ok?
Forte abraço!
Nelio

**Comment by vitorsacramento** [comment]
Boa tarde, professor e obrigado pela resposta. Ah, entendi! Coisa de
iniciante RS. Obrigado pelo esclarecimento e também pelo excelente material.

Em sex, 1 de fev de 2019 15:07, acenelio <notifications@github.com escreveu:
